doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                # configure these for your database server
                # use postgresql for PostgreSQL
                # use sqlite for SQLite
                driver: 'mysql'
                server_version: '5.7'

                # only needed for MySQL
                charset: utf8mb4
                default_table_options:
                    charset: utf8mb4
                    collate: utf8mb4_unicode_ci

                url: '%env(resolve:DATABASE_URL)%'
            cash_colis:
                driver: 'mysql'
                server_version: '5.7'

                # only needed for MySQL
                charset: utf8mb4
                default_table_options:
                    charset: utf8mb4
                    collate: utf8mb4_unicode_ci

                url: '%env(resolve:DATABASE_CAHS_COLIS_URL)%'
    orm:
        default_entity_manager: default
        auto_generate_proxy_classes: true        
        entity_managers:
            default:
                connection: default
                naming_strategy: doctrine.orm.naming_strategy.underscore
                auto_mapping: true
                mappings:
                    Back:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity'
                        prefix: 'App\Entity'
                        alias: App
            cash_colis:
                connection: cash_colis
                naming_strategy: doctrine.orm.naming_strategy.underscore
                #auto_mapping: true                
                mappings:
                    cash_colis:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity/Cash_colis'
                        prefix: 'App\Entity'
                        alias: cash_colis            
