framework:
    secret: '%env(APP_SECRET)%'
    #csrf_protection: true
    #http_method_override: true

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        handler_id: null

    #esi: true
    #fragments: true
    php_errors:
        log: true

    assets:
        packages:
            qobd_web_images:
                base_path: ressources/image
            qobd_web_css:
                base_path: ressources/css
            qobd_web_js: 
                base_path: ressources/js
            bootstrap_css:
                base_path: ressources/css/bootstrap
            bootstrap_js:
                base_path: ressources/js/bootstrap
            datatable_dir:
                base_path: ressources/datatable
            font_awsome_css:
                base_path: ressources/fontawesome-web-5.11.2/css
            font_awsome_js:
                base_path: ressources/fontawesome-web-5.11.2/js
            fos_route_js:
                base_path: ressources/../../web/js
            theme_coreui:
                base_path: ressources/themes/coreui
            theme_default:
                base_path: ressources/themes/default
            download_dir:
                base_path: ressources/download

