twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes: ['bootstrap_4_layout.html.twig']
    globals:
        search: '@App\Services\SearchToView'
        chat: '@App\Services\ChatToView'
        email_dir: '%file.setting.file.download_dir%'
