# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    app.name: '/QOBDWeb'
    app.name.base_dir: '%app.name%'
    download_dir: 'ressources/download'

    agent_dir: 'agent/avatars'
    setting.catalogue_dir: 'setting/catalogue'
    setting.file_dir: 'setting/files'
    setting.image_dir: 'setting/image'
    pdf.bill_dir: 'pdf/order'
    pdf.quote_dir: 'pdf/quote'
    pdf.delivery_dir: 'pdf/delivery'


    resource.download_dir: '%app.name.base_dir%/%download_dir%'
    file.download_dir: '%resource.download_dir%'
    file.agent.download_dir: '%file.download_dir%/%agent_dir%'
    file.setting.catalogue.download_dir: '%file.download_dir%/%setting.catalogue_dir%'
    file.setting.file.download_dir: '%file.download_dir%/%setting.file_dir%'
    file.setting.image.download_dir: '%file.download_dir%/%setting.image_dir%'
    file.pdf.bill.download_dir: '%file.download_dir%/%pdf.bill_dir%'
    file.pdf.quote.download_dir: '%file.download_dir%/%pdf.quote_dir%'
    file.pdf.delivery.download_dir: '%file.download_dir%/%pdf.delivery_dir%'

    file.setting.email: '%app.name.base_dir%/templates/email/files'
    file.setting.text: '%app.name.base_dir%/templates/document/files'

    abs.public: '%app.name.base_dir%/public'
    abs.resource.download_dir: '%abs.public%/%download_dir%'
    abs.file.download_dir: '%abs.resource.download_dir%'
    abs.file.agent.download_dir: '%abs.file.download_dir%/%agent_dir%'
    abs.file.setting.catalogue.download_dir: '%abs.file.download_dir%/%setting.catalogue_dir%'
    abs.file.setting.file.download_dir: '%abs.file.download_dir%/%setting.file_dir%'
    abs.file.setting.image.download_dir: '%abs.file.download_dir%/%setting.image_dir%'
    abs.file.pdf.bill.download_dir: '%abs.file.download_dir%/%pdf.bill_dir%'
    abs.file.pdf.quote.download_dir: '%abs.file.download_dir%/%pdf.quote_dir%'
    abs.file.pdf.delivery.download_dir: '%abs.file.download_dir%/%pdf.delivery_dir%'

    logo_dir: '%file.download_dir%/setting/image'

    tax.type.ht: 101
    tax.type.ttc: 102
    tax.type.tva_marge: 103
    session_max_idle_time: 3800
    secret: '%env(APP_SECRET)%'
    email.url: '%env(MAILER_URL)%'
    email.swiftmailer: true

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: false       # Allows optimizing the container by removing unused services; this also means
                            # fetching services directly from the container via $container->get() won't work.
                            # The best practice is to be explicit about your dependencies anyway.
        bind:
            $logo_dir: '%file.download_dir%/setting/image'
            $avatar_dir: '%file.download_dir%/agent/avatars'
            $catalogue_dir: '%file.download_dir%/setting/catalogue'
            $maxIdleTime: '%session_max_idle_time%'
            $root_dir: '%app.name.base_dir%/public'
            $email_swiftmailer: '%email.swiftmailer%'
            $email_url: '%email.url%'
            $tax_type_ht: '%tax.type.ht%'
            $tax_type_ttc: '%tax.type.ttc%'
            $tax_type_tva_marge: '%tax.type.tva_marge%'

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']
    
    # authentication success event listener
    # app/security/interactive_login_listener:
    #     class: App\Services\SecurityManager
    #     tags:
    #         - { name: kernel.event_listener, event: security.interactive_login, method: onAuthenticationSuccess }
    
    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    # Symfony\Component\Serializer\Normalizer\ObjectNormalizer:
    #    class: Symfony\Component\Serializer\Normalizer\ObjectNormalizer
    #    public: false
    #    tags:
    #      - { name: 'serializer.normalizer' }

    # Symfony\Component\Serializer\Normalizer\GetSetMethodNormalizer:
    #    class: Symfony\Component\Serializer\Normalizer\GetSetMethodNormalizer
    #    public: false
    #    tags:
    #      - { name: 'serializer.normalizer' }
